name: Compile

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make
      uses: docker://teeed/stm32-toolchain-make-action
    - name: Move artifacts
      run: mkdir artifacts && cp build/canpybara.bin build/canpybara.hex build/canpybara.elf artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: binaries
        path: artifacts
